version: '2'

services:
  infinispan-server:
    image: jboss/infinispan-server:10.0.0.Beta3
    ports:
    - "11222:11222"
    container_name: infinispan
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge